version: "3"
services:
  node-do-zero-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: "default"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "node-do-zero-db"
    ports:
      - "5435:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
